apiVersion: apps/v1
kind: Deployment
metadata:
 name: board-deployment
 labels:
  app: game
spec:
 replicas: 2
 selector:
  matchLabels:
   app: game
 template:
  metadata:
    name: board-app
    labels:
     app: game
  spec:
    containers:
     - name: boardapp
       image: devopsproject1.azurecr.io/boardgame-app:latest
       ports:
        - containerPort: 8080
