apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
spec:
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: boardgamee
        image: devopsproject1.azurecr.io/boardgame-app:latest
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
spec:
  selector:
    app: game
  ports:
    - targetPort: 8080    
      port: 8081           
  type: LoadBalancer
